(()=>{
const MAP_REV='20260822-starter-homes-v1';
const DEFAULT_MAP=`./city/plate_map.html?mode=opening&v=${MAP_REV}`;
const MAP_URL=new URLSearchParams(location.search).get('map')||DEFAULT_MAP;
const STEPS=['关于你','住所与工作','自定义主播','确认'];
const HOMES=[
{id:'lx_share',name:'落霞合租屋',fullName:'落霞区 / 落霞合租屋',district:'落霞区',tenure:'合租',note:'大学城南的普通两居合租，租金低，隔音一般',rent:1800,deposit:3600,cost:'月租 RMB 1,800 / 押二付一'},
{id:'pj_apt',name:'浦江人才公寓',fullName:'雨石与浦江区 / 浦江人才公寓',district:'雨石与浦江区',tenure:'租住',note:'园区外的小户型人才公寓，适合园区通勤',rent:2600,deposit:5200,cost:'月租 RMB 2,600 / 押二付一'},
{id:'gl_yunting',name:'鼓岭云庭公寓',fullName:'鼓岭区 / 鼓岭云庭公寓',district:'鼓岭区',tenure:'租住',note:'老城精装单间，日常配套完整',rent:3200,deposit:6400,cost:'月租 RMB 3,200 / 押二付一'},
{id:'xz_jiayuan',name:'西洲嘉苑',fullName:'西洲区 / 西洲嘉苑',district:'西洲区',tenure:'租住',note:'靠近直播产业带的高层单间',rent:3900,deposit:7800,cost:'月租 RMB 3,900 / 押二付一'},
{id:'gl_wutong',name:'梧桐里步行房',fullName:'鼓岭区 / 梧桐里',district:'鼓岭区',tenure:'租住',note:'老城区步行房，生活方便，楼梯和邻里声较近',rent:2200,deposit:4400,cost:'月租 RMB 2,200 / 押二付一'},
{id:'pj_village',name:'浦江城中村单间',fullName:'雨石与浦江区 / 浦江城中村',district:'雨石与浦江区',tenure:'租住',note:'租金最低，离园区近，公共空间紧凑',rent:1500,deposit:3000,cost:'月租 RMB 1,500 / 押二付一'},
{id:'wx_home',name:'乌溪自宅',fullName:'乌溪区 / 乌溪自宅',district:'乌溪区',tenure:'自有',note:'带小型药剂工坊的自有住宅',rent:0,deposit:0,cost:'自有房产 / 无月租'},
{id:'mh_youth_apt',name:'明湖青年公寓',fullName:'明湖区 / 明湖青年公寓',district:'明湖区',tenure:'租住',note:'城区小单间，公交和生活配套方便',rent:3200,deposit:3200,cost:'月租 RMB 3,200 / 押一付一'},
{id:'dt_town_rental',name:'东塘镇口出租屋',fullName:'东塘区 / 东塘镇口出租屋',district:'东塘区',tenure:'租住',note:'镇口低租单间，生活成本低但进城较远',rent:1400,deposit:1400,cost:'月租 RMB 1,400 / 押一付一'},
{id:'qp_foothill_share',name:'青屏山脚合租院',fullName:'青屏山风景区 / 青屏山脚合租院',district:'青屏山风景区',tenure:'合租',note:'独立卧室、共用厨房，末班公交较早',rent:1800,deposit:1800,cost:'月租 RMB 1,800 / 押一付一'}];
const JOBS=[
{name:'暂时无业',place:null,node:null,monthly:0,daily:0,hours:'自由安排',kind:'free'},
{name:'打印店店员',place:'落霞区 / 落霞打印店',node:'lx_print',monthly:4500,daily:205,hours:'09:00-18:00',kind:'service'},
{name:'快递驿站店员',place:'鼓岭区 / 鼓岭快递驿站',node:'gl_parcel',monthly:4800,daily:220,hours:'08:30-18:30',kind:'service'},
{name:'便利店店员',place:'明湖区 / 明湖通宵便利',node:'mh_mart',monthly:4700,daily:215,hours:'14:00-22:00',kind:'service'},
{name:'电竞舱值班员',place:'西洲区 / 星芒电竞训练直播舱',node:'xz_esports',monthly:5200,daily:235,hours:'16:00-00:00',kind:'live'},
{name:'加油站夜班店员',place:'东塘区 / 东塘加油站',node:'dt_gas',monthly:5600,daily:255,hours:'20:00-06:00',kind:'service'},
{name:'录音棚助理',place:'西洲区 / 极光数码声学录音棚',node:'xz_sound_studio',monthly:5400,daily:245,hours:'11:00-20:00',kind:'live'},
{name:'剧院场务',place:'西洲区 / 西洲大剧院',node:'xz_theatre',monthly:4600,daily:210,hours:'13:00-22:00',kind:'live'},
{name:'宠物诊疗所助理',place:'鼓岭区 / 梧桐里宠物医疗中心',node:'gl_pet',monthly:5000,daily:225,hours:'10:00-19:00',kind:'medical'},
{name:'医院前台助理',place:'明湖区 / 明湖中心医院',node:'mh_hospital',monthly:5800,daily:260,hours:'08:00-17:00',kind:'medical'},
{name:'实验楼值班助理',place:'落霞区 / 落霞实验楼',node:'lx_lab',monthly:6000,daily:270,hours:'18:00-02:00',kind:'academy'},
{name:'研创园行政助理',place:'雨石与浦江区 / 浦江研创园',node:'ys_rdpark',monthly:6200,daily:280,hours:'09:30-18:30',kind:'office'},
{name:'扎染作坊学徒',place:'乌溪区 / 乌溪扎染作坊',node:'wx_dye',monthly:4200,daily:190,hours:'10:00-19:00',kind:'craft'}];
const CATEGORIES=['杂谈','游戏','唱歌','ASMR','绘画','舞蹈','户外','美食','虚拟主播','综合内容'];
const PROFILE_FIELDS=['一句话定位','外貌','公开形象','真实性格','说话方式','直播风格','兴趣与擅长','生活习惯','喜恶与雷区','个人经历','对观众的态度','线上线下差异'];
const state={step:1,gender:'男性',home:null,job:JOBS[0],mapTarget:'player',categories:new Set(['杂谈']),profile:null,art:{type:'',src:''},streamerHome:null};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const value=id=>$(id).value.trim();
let toastTimer=0;
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('on');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('on'),2200)}
function heatLabel(n){return n<20?'小透明':n<40?'小有关注':n<60?'稳定主播':n<80?'热门主播':n<95?'头部主播':'现象级'}
function renderSteps(){document.querySelector('#steps').innerHTML=STEPS.map(function(step,i){return '<button class="step-tab '+(state.step===i+1?'active ':'')+(state.step>i+1?'done':'')+'" data-step="'+(i+1)+'"><span>0'+(i+1)+'</span><b>'+step+'</b></button>'}).join('');document.querySelectorAll('.step-tab').forEach(function(b){b.onclick=function(){go(+b.dataset.step)}})}
function homeCostText(h){return h&&h.cost||'费用待确认'}
function openingMapApi(){try{var frame=document.querySelector('#opening-map-iframe');return frame&&frame.contentWindow.PLATE_MAP||null}catch(_){return null}}
function modalMapApi(){try{var frame=document.querySelector('#map-iframe');return frame&&frame.contentWindow.PLATE_MAP||null}catch(_){return null}}
function mapApi(){return openingMapApi()}
function quoteFor(job){if(!state.home||!job||!job.node)return null;var api=mapApi();if(!api||!api.quote)return null;try{var all=api.quote(state.home.id,job.node);return all&&(all.transit||all.walk||all.taxi)||null}catch(_){return null}}
function routeLabel(route){return route?route.min+' 分钟（单程） / '+route.km+' 公里 / 单程 RMB '+route.yuan:'等待地图路网'}
function jobCommuteText(job){if(!job||!job.node)return '无需固定通勤';var r=quoteFor(job);if(!state.home)return '选定住所后计算通勤';return r?'公交优先 / '+routeLabel(r):'当前住所暂未算出路线'}
function metric(label,value,sub){return '<div class="work-metric"><span>'+esc(label)+'</span><b>'+esc(value)+'</b>'+(sub?'<small>'+esc(sub)+'</small>':'')+'</div>'}
function workMetricsHtml(job,route){var employed=job&&job.monthly;if(!employed)return '<div class="commute-head"><span>岗位与通勤</span><small>当前选择：暂时无业</small></div><div class="work-metrics">'+metric('月收入','无固定收入','可以从自由安排开始')+metric('班次','自由安排','没有固定上班时间')+metric('单程通勤','无需通勤','—')+metric('路线距离','—','—')+metric('单程交通费','—','—')+'</div>';var wait=state.home?(route?'':'路线计算中'):'先选住所';return '<div class="commute-head"><span>岗位与通勤</span><small>通勤按公交优先、单程估算</small></div><div class="work-metrics">'+metric('月收入','RMB '+job.monthly.toLocaleString()+' / 月','岗位固定月薪')+metric('班次',job.hours,'每天工作时段')+metric('单程通勤',route?route.min+' 分钟':wait,route?'每天往返约 '+(route.min*2)+' 分钟':'')+metric('路线距离',route?route.km+' 公里':wait,'住所到工作地点')+metric('单程交通费',route?'RMB '+route.yuan:wait,route?'往返约 RMB '+(route.yuan*2):'')+'</div>'}
function renderJobs(){var el=document.querySelector('#jobs');if(!el)return;el.innerHTML=JOBS.map(function(j,i){return '<button data-job="'+i+'">'+esc(j.name)+'</button>'}).join('');el.querySelectorAll('[data-job]').forEach(function(b){b.onclick=function(){setJob(JOBS[+b.dataset.job])}})}
function updatePickSummary(){var home=document.querySelector('#map-pick-home'),work=document.querySelector('#map-pick-work');if(home)home.textContent=state.home?state.home.name:'未选择';if(work)work.textContent=state.job&&state.job.monthly?state.job.name:'暂时无业'}
function updateHomeInspector(){var h=state.home;var name=document.querySelector('#home-name'),meta=document.querySelector('#home-meta'),cost=document.querySelector('#home-cost');if(!name)return;name.textContent=h?h.name:'尚未选择住所';name.classList.toggle('empty',!h);meta.textContent=h?h.fullName+' / '+h.tenure+' / '+h.note:'全城八个城区都有可选住宅；点击粉色节点查看。';cost.textContent=h?homeCostText(h):'租金与押金将在这里显示';updatePickSummary()}
function updateWorkInspector(){var j=state.job,r=j&&j.monthly?quoteFor(j):null;var name=document.querySelector('#work-name');if(!name)return;name.textContent=j&&j.monthly?j.name:'暂时无业';document.querySelector('#work-meta').textContent=j&&j.place?j.place+(state.home?'':' / 选好住所后计算通勤'):'可以先选住所，也可以先挑工作；暂时无业同样可以继续。';document.querySelector('#commute-card').innerHTML=workMetricsHtml(j,r);updatePickSummary()}
function renderMapInspector(){updateHomeInspector();updateWorkInspector()}
function setOpeningTarget(target){state.mapTarget=target==='work'?'work':'player';var homeBtn=document.querySelector('#map-home-mode'),workBtn=document.querySelector('#map-work-mode');homeBtn.classList.toggle('on',state.mapTarget==='player');workBtn.classList.toggle('on',state.mapTarget==='work');document.querySelector('#map-mode-title').textContent=state.mapTarget==='work'?'挑一份开局工作':'挑一个开局住处';document.querySelector('#map-mode-hint').textContent=state.mapTarget==='work'?(state.home?'先比较月收入和班次，再看从当前住所出发的单程通勤。':'可以先挑岗位；选好住所后，通勤时间、距离和费用会自动补全。'):'每个城区都有住宅选项；点击粉色节点查看租金和住处特点。';var api=openingMapApi();try{if(api&&api.setOpeningTarget)api.setOpeningTarget(state.mapTarget==='work'?'work':'home');if(state.mapTarget==='work'&&state.home&&state.job&&state.job.node&&api)api.plan(state.job.node)}catch(_){}renderMapInspector()}
function setJob(job){if(!job)return;state.job=job;var api=openingMapApi();try{if(api&&state.home&&job.node)api.plan(job.node);else if(api&&api.clearTrip)api.clearTrip()}catch(_){}updateWorkInspector();toast(job.monthly?'已选择工作：'+job.name:'已选择暂时无业')}
function renderTags(){$('#category-tags').innerHTML=CATEGORIES.map(c=>`<button type="button" class="tag ${state.categories.has(c)?'on':''}" data-cat="${c}">${c}</button>`).join('');document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{const c=b.dataset.cat;state.categories.has(c)?state.categories.delete(c):state.categories.add(c);if(!state.categories.size)state.categories.add('杂谈');renderTags()})}
function setHome(home,target){if(!home)return;target=target||state.mapTarget;if(target==='player'){state.home=home;var api=openingMapApi();try{if(api){api.setState({district:home.district||'',player:{at:home.id},actors:[],events:[]});if(state.job&&state.job.node)api.plan(state.job.node);else if(api.clearTrip)api.clearTrip()}}catch(_){}renderMapInspector();setOpeningTarget('work');toast('初始住所已选择：'+home.name)}else if(target==='work'){setJob(home);return}else{state.streamerHome=home;document.querySelector('#streamer-home').textContent=home.fullName;closeMap()}}
function bindFrame(){var frame=document.querySelector('#map-iframe');try{var api=frame.contentWindow.PLATE_MAP;if(api)api.onPick(function(node){handleMapPick(node)})}catch(_){} }
function bindOpeningFrame(){var frame=document.querySelector('#opening-map-iframe');try{var api=frame.contentWindow.PLATE_MAP;if(api){api.onPick(function(node){handleMapPick(node)});if(api.setOpeningTarget)api.setOpeningTarget(state.mapTarget==='work'?'work':'home');if(state.home)api.setState({district:state.home.district||'',player:{at:state.home.id},actors:[],events:[]})}}catch(_){} }
function renderMapQuick(){var box=document.querySelector('#quick-homes');if(!box)return;box.innerHTML=HOMES.map(function(h,i){return '<button class="quick" data-home="'+i+'">'+esc(h.name)+' / '+esc(homeCostText(h))+'</button>'}).join('');box.querySelectorAll('[data-home]').forEach(function(btn){btn.onclick=function(){setHome(HOMES[+btn.dataset.home],'streamer')}})}
function closeMap(){var modal=document.querySelector('#map-modal');if(modal)modal.classList.remove('on')}
function syncMapFullscreen(){var card=document.querySelector('#opening-map-card'),btn=document.querySelector('#map-fullscreen');if(!card||!btn)return;var on=document.fullscreenElement===card;btn.textContent=on?'× 退出全屏':'⛶ 全屏地图';card.classList.toggle('is-fullscreen',on);setTimeout(function(){var api=openingMapApi();try{if(api)api.fitAll(0)}catch(_){}},120)}
function toggleMapFullscreen(){var card=document.querySelector('#opening-map-card');if(!card)return;if(document.fullscreenElement===card){document.exitFullscreen()}else if(card.requestFullscreen){card.requestFullscreen()}}
function openMap(target){if(target==='player'||target==='work'){setOpeningTarget(target);go(2);return}state.mapTarget='streamer';document.querySelector('#map-title').textContent='选择自定义主播住所';document.querySelector('#map-modal').classList.add('on');var frame=document.querySelector('#map-iframe');if(!frame.getAttribute('src'))frame.src=MAP_URL;var api=modalMapApi();try{if(api&&api.setOpeningTarget)api.setOpeningTarget('home')}catch(_){} }
function handleMapPick(node){if(!node||!node.id)return;var knownHome=HOMES.find(function(h){return h.id===node.id});if(state.mapTarget==='player'){if(knownHome)return setHome(Object.assign({},knownHome,{name:node.name,fullName:node.fullName||knownHome.fullName,district:node.district||knownHome.district}));toast('请点击地图上的粉色住宅节点');return}if(state.mapTarget==='work'){var knownJob=JOBS.find(function(j){return j.node===node.id});if(knownJob)return setJob(knownJob);toast('请选择已加入开局岗位池的工作节点');return}if(state.mapTarget==='streamer'&&node.archetype==='living')return setHome({id:node.id,name:node.name,fullName:node.fullName||node.district+' / '+node.name,district:node.district,tenure:'租住',note:node.draw||'从地图选择的居住地点',rent:0,deposit:0,cost:'费用由开局后设定'},'streamer');toast('请选择住所类地点')}
function updateArt(src,type){state.art={src,type};const box=$('#art-preview'),img=$('#art-img');if(src){img.src=src;box.classList.add('has')}else{img.removeAttribute('src');box.classList.remove('has')}}
function streamerInput(){const heat=+$('#streamer-heat').value;return{name:value('#streamer-name'),handle:value('#streamer-handle'),age:+value('#streamer-age')||23,home:state.streamerHome?.fullName||'',categories:[...state.categories],heat,heatLabel:heatLabel(heat),followers:+value('#streamer-followers')||0,captains:+value('#streamer-captains')||0,hours:value('#streamer-hours'),tone:value('#streamer-tone'),seed:value('#streamer-seed')}}
function localProfile(d){const focus=d.categories.join('、'),seed=d.seed||'她有完整的工作与私人生活，不会只围绕某个观众行动。';return{
'一句话定位':`${d.handle||d.name}是一名以${focus}为主的${d.heatLabel}主播，镜头前有稳定辨识度，线下仍过着具体而普通的城市生活。`,
'外貌':'外貌以玩家提供的立绘为准；日常穿着重视舒适与镜头效果，离开直播环境后会明显放松。',
'公开形象':`直播中保持清晰的内容节奏，擅长把零散话题接成自然的节目效果。${d.tone?`整体气质偏${d.tone}。`:''}`,
'真实性格':'有自己的判断、情绪和生活安排。对熟人会逐渐放松，对越界要求会直接拉开距离。',
'说话方式':'语气自然，回应会结合正在进行的内容；不会因为单条弹幕就停下整场直播。',
'直播风格':`常用内容为${focus}，常用直播时间${d.hours||'不固定'}。热度与观众规模会影响弹幕密度和被注意到的概率。`,
'兴趣与擅长':`围绕${focus}积累了稳定经验，也会在直播外保留不公开的私人爱好。`,
'生活习惯':`${d.home?`目前居住在${d.home}。`:''}开播前会做基础准备，下播后通常先处理设备、消息和第二天安排。`,
'喜恶与雷区':'重视个人隐私与现实边界；不喜欢观众以打赏为理由干涉私人生活。',
'个人经历':seed,
'对观众的态度':'会记住长期出现、发言有辨识度的观众，但公开直播中仍需平衡整个直播间。',
'线上线下差异':'镜头前更善于维持情绪和节奏；线下表达更直接，也有疲惫、走神和不想社交的时候。'}}function renderProfile(){const d=streamerInput();$('#generated').classList.toggle('on',!!state.profile);if(!state.profile)return;$('#profile-grid').innerHTML=PROFILE_FIELDS.map(k=>`<div class="field ${['一句话定位','个人经历'].includes(k)?'wide':''}"><label>${k}</label><textarea class="control" data-profile="${k}">${esc(state.profile[k]||'')}</textarea></div>`).join('');document.querySelectorAll('[data-profile]').forEach(t=>t.oninput=()=>{state.profile[t.dataset.profile]=t.value;updateBookPreview()});updateBookPreview()}
function requestHostGeneration(payload){if(window.parent===window)return Promise.resolve(null);return new Promise(resolve=>{const id='profile-'+Date.now(),timer=setTimeout(()=>{removeEventListener('message',on);resolve(null)},12000);function on(e){const d=e.data;if(d?.channel==='linjiang-opening'&&d.kind==='response'&&d.id===id){clearTimeout(timer);removeEventListener('message',on);resolve(d.ok?d.payload?.profile:null)}}addEventListener('message',on);parent.postMessage({channel:'linjiang-opening',kind:'request',id,action:'generateStreamerProfile',payload},'*')})}
async function generateProfile(){const d=streamerInput();if(!d.name||!d.handle){toast('先填写主播姓名和网名');return}const btn=$('#generate-profile'),status=$('#generate-status');btn.disabled=true;btn.textContent='生成中…';status.textContent='\u6b63\u5728\u751f\u6210\u6863\u6848';let external=null;try{external=await requestHostGeneration(d)}catch(_){}state.profile=external||localProfile(d);setTimeout(()=>{renderProfile();btn.disabled=false;btn.textContent='重新生成人设档案';status.textContent=external?'\u5df2\u751f\u6210':'\u5df2\u751f\u6210'},450)}
function worldbookText(){if(!state.profile)return'';const d=streamerInput();return `<自定义主播：${d.name}／${d.handle}>\n\n基础资料:\n  姓名: ${d.name}\n  主播网名: ${d.handle}\n  年龄: ${d.age}\n  住所: ${d.home||'未设置'}\n  直播分类: [${d.categories.join(', ')}]\n  热度: ${d.heat}（${d.heatLabel}）\n  粉丝数: ${d.followers}\n  舰长数: ${d.captains}\n  常用直播时间: ${d.hours||'不固定'}\n\n人设档案:\n${PROFILE_FIELDS.map(k=>`  ${k}: ${state.profile[k]||''}`).join('\n')}\n\n约束:\n  - 她拥有独立生活、工作、人际关系和判断，不围绕玩家单独存在\n  - 打赏、关注和舰长身份不直接换算为私人好感\n  - 当前所在位置、直播开关、好感和生理状态以MVU动态数据为准\n\n</自定义主播：${d.name}／${d.handle}>`}
function updateBookPreview(){const d=streamerInput(),text=worldbookText();$('#book-name').textContent=text?`自定义主播｜${d.name}／${d.handle}`:'尚未生成';$('#book-content').textContent=text||'填写主播资料并生成人设档案后，这里会显示世界书正文预览。'}
function syncInputs(){const n=value('#streamer-name'),h=value('#streamer-handle');$('#art-name').textContent=n||'新主播';$('#art-handle').textContent=(h||'STREAMER').toUpperCase();$('#art-monogram').textContent=(n||h||'S').slice(0,1)}
function validate(step){if(step===1&&!value('#player-name')){toast('请填写玩家姓名或常用称呼');return false}if(step===2&&!state.home){toast('请先从地图选择初始住所');return false}return true}
function renderConfirm(){var player=value('#player-name')||'未命名玩家',handle=value('#player-handle')||'未设置网名',job=state.job,home=state.home;document.querySelector('#confirm-player').textContent=player;document.querySelector('#confirm-lines').innerHTML=[['玩家档案',player+' / '+state.gender+' / '+(value('#player-age')||24)+'岁'],['直播网名',handle],['初始住所',home?home.fullName+' / '+homeCostText(home):'未选择'],['初始工作',job.name],['收入与时间',job.monthly?'月薪约 RMB '+job.monthly.toLocaleString()+' / '+job.hours:'无固定收入'],['通勤估算',job.monthly?jobCommuteText(job):'无需通勤'],['自定义主播',state.profile?value('#streamer-name')+' / '+value('#streamer-handle'):'未追加']].map(function(row){return '<div class="confirm-line"><span>'+row[0]+'</span><b>'+esc(row[1])+'</b></div>'}).join('');updateBookPreview()}
function go(step){if(step>state.step&&!validate(state.step))return;state.step=Math.max(1,Math.min(4,step));document.body.classList.toggle('life-map-step',state.step===2);document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',+p.dataset.panel===state.step));renderSteps();$('#prev').classList.toggle('hidden',state.step===1);$('#next').textContent=state.step===4?'生成开局配置':'继续';if(state.step===4)renderConfirm();if(state.step===2)setTimeout(function(){var api=openingMapApi();try{if(api)api.fitAll(0)}catch(_){}},80);scrollTo({top:0,behavior:'smooth'})}
function emptyExperience(){return{近期性经验次数:0,露出经验:0,自慰经验:0,排泄调教经验:0,道具调教经验:0,凌辱调教经验:0,隐奸经验:0,青奸经验:0,睡奸经验:0,催眠奸经验:0,情趣扮演经验:0,盗摄经验:0,性直播经验:0}}
function emptyDevelopment(){return{口腔:{档位:0,评语:''},胸:{档位:0,评语:''},小穴:{档位:0,评语:''},肛门:{档位:0,评语:''}}}
function commuteForCurrentJob(){return state.job&&state.job.node?quoteFor(state.job):null}
function openingPayload(){var d=streamerInput(),pname=value('#player-name'),job=state.job,commute=commuteForCurrentJob(),mvu={'世界信息':{'年历':'2026-04-01','时间':{'时钟':'08:00','时段':'朝'},'位置':{'区域':state.home.fullName,'场所':'家中'}},'玩家信息':{'档案':{'姓名':pname,'性别':state.gender,'年龄':+value('#player-age')||24,'网名':value('#player-handle'),'补充设定':value('#player-note')},'体力':100,'金钱':20000,'工作':{'职业':job.place?job.name:null,'地点':job.place,'日收入':job.daily,'工作时间':job.place?job.hours:null,'今日已上班':false,'通勤':commute?{'方式':'公交优先','分钟':commute.min,'距离公里':commute.km,'费用':commute.yuan}:null},'居住地':state.home.fullName,'房产':{[state.home.name]:{'名称':state.home.name,'区域':state.home.fullName,'产权':state.home.tenure,'描述':state.home.note,'月租':state.home.rent||0,'押金':state.home.deposit||0,'售价':state.home.sale||0,'费用说明':homeCostText(state.home)}}}};if(state.profile)mvu['对象信息']={[d.name]:{'羁绊':{'好感度':0,'顺从度':0,'心情':'开朗'},'位置':{'区域':d.home,'场所':'家中'},'性经历':emptyExperience(),'开发度':emptyDevelopment(),'生理':{'性欲度':0,'体力':100,'尿意':20,'异常状态':[]},'直播':{'开播':false,'标题':'','人数':0,'热度':d.heat,'粉丝数':d.followers,'舰长数':d.captains}}};return{mvu:mvu,worldbook:state.profile?{name:'自定义主播 / '+d.name+' / '+d.handle,keys:[d.name,d.handle],content:worldbookText()}:null,ui:state.profile?{name:d.name,handle:d.handle,art:state.art}:null}}
function finish(){const payload=openingPayload();if(window.parent!==window)parent.postMessage({channel:'linjiang-opening',kind:'event',type:'commitPreview',payload},'*');navigator.clipboard?.writeText(JSON.stringify(payload,null,2)).catch(()=>{});console.log('[临江开局配置]',payload);toast('开局配置已生成，并已尝试复制到剪贴板')}
renderSteps();renderMapInspector();renderTags();go(1);var initialMap=document.querySelector('#opening-map-iframe');if(initialMap&&!initialMap.getAttribute('src')){initialMap.src=MAP_URL+'&target=home';initialMap.addEventListener('load',function(){setTimeout(bindOpeningFrame,200)})}
$('#gender-segment').onclick=e=>{const b=e.target.closest('button');if(!b)return;state.gender=b.dataset.value;$('#gender-segment').querySelectorAll('button').forEach(x=>x.classList.toggle('on',x===b))};
document.querySelectorAll('[data-open-map]').forEach(b=>b.onclick=()=>openMap(b.dataset.openMap));
$('#map-close').onclick=closeMap;$('#map-modal').onclick=e=>{if(e.target===$('#map-modal'))closeMap()};
renderMapQuick();
$('#map-iframe').addEventListener('load',()=>setTimeout(bindFrame,350));document.querySelector('#map-home-mode').onclick=()=>setOpeningTarget('player');document.querySelector('#map-work-mode').onclick=()=>setOpeningTarget('work');document.querySelector('#change-home').onclick=()=>setOpeningTarget('player');document.querySelector('#change-work').onclick=()=>setOpeningTarget('work');document.querySelector('#map-fullscreen').onclick=toggleMapFullscreen;document.addEventListener('fullscreenchange',syncMapFullscreen);
addEventListener('message',e=>{const d=e.data;if(d?.channel==='linjiang-map'&&d.type==='pick')handleMapPick(d.payload)});
$('#streamer-heat').oninput=e=>$('#heat-value').textContent=e.target.value;
['#streamer-name','#streamer-handle'].forEach(id=>$(id).addEventListener('input',syncInputs));
$('#apply-art-url').onclick=()=>{const u=value('#art-url');if(!u)return toast('先填写网络立绘链接');updateArt(u,'url')};
$('#art-file').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>updateArt(r.result,'upload-preview');r.readAsDataURL(f)};
$('#generate-profile').onclick=generateProfile;$('#prev').onclick=()=>go(state.step-1);$('#next').onclick=()=>state.step===4?finish():go(state.step+1);
})();
