(()=>{'use strict';
const BALANCE_KEY='airp_arcade_tokens_v1',PROFILE_KEY='airp_arcade_token_progress_v1';
const BASE_FISH=['clown','jelly','puffer','turtle','shark','whale'];
const BASE_SLOT=['cherry','lemon','grape','watermelon','bar','seven','microphone','gift','rocket','crown'];
const BASE_AUCTION=['porcelain','jade','bronze','painting','coin','curio','furniture'];
const GOALS={fishing:6,scratch:6,slots:6,auction:5},ADVANCED={fishing:200,scratch:7,slots:7,auction:7};
const ICON={fishing:'assets/token/pearl-token.svg',scratch:'assets/token/star-fragment.svg',slots:'assets/token/arcade-chip.svg',auction:'assets/token/arcade-chip.svg'};
const fresh=()=>({version:2,unlocks:{fishing:false,scratch:false,slots:false,auction:false},advanced:{fishing:false,scratch:false,slots:false,auction:false},collections:{fishing:{},scratch:{},slots:{},auction:{}},earned:{fishing:0,scratch:0,slots:0,auction:0}});
const readJSON=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')||f}catch(_){return f}};
const saveJSON=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch(_){}};
const profile=()=>{const f=fresh(),p=readJSON(PROFILE_KEY,{});return{...f,...p,unlocks:{...f.unlocks,...(p.unlocks||{})},advanced:{...f.advanced,...(p.advanced||{})},collections:{fishing:{...(p.collections?.fishing||{})},scratch:{...(p.collections?.scratch||{})},slots:{...(p.collections?.slots||{})},auction:{...(p.collections?.auction||{})}},earned:{...f.earned,...(p.earned||{})}}};
const wallet=()=>{const p=readJSON(BALANCE_KEY,{});return{balance:Math.max(0,Math.floor(Number(p.balance)||0)),totalEarned:Math.max(0,Math.floor(Number(p.totalEarned)||0))}};
function writeProfile(p){saveJSON(PROFILE_KEY,p);dispatchEvent(new CustomEvent('airp-token:profile',{detail:p}))}
function setBalance(next,total){const v={balance:Math.max(0,Math.floor(next)),totalEarned:Math.max(0,Math.floor(total)),updatedAt:Date.now()};saveJSON(BALANCE_KEY,v);dispatchEvent(new CustomEvent('airp-token:update',{detail:v}));return v}
function unlockCheck(game,p){const collectionCount=Object.keys(p.collections[game]).filter(k=>k!=='__caught').length;const open=collectionCount>=GOALS[game];if(open&&!p.unlocks[game]){p.unlocks[game]=true;dispatchEvent(new CustomEvent('airp-token:unlock',{detail:{game,count:collectionCount,target:GOALS[game],tier:1}}))}const advancedCount=game==='fishing'?Number(p.collections.fishing.__caught||0):collectionCount;const advanced=advancedCount>=ADVANCED[game];if(advanced&&!p.advanced[game]){p.advanced[game]=true;dispatchEvent(new CustomEvent('airp-token:unlock',{detail:{game,count:advancedCount,target:ADVANCED[game],tier:2}}))}return open}
function record(game,d={}){const p=profile();if(game==='fishing'){if(d.captured&&BASE_FISH.includes(d.fishType))p.collections.fishing[d.fishType]=true;p.collections.fishing.__caught=(Number(p.collections.fishing.__caught)||0)+(d.captured?1:0)}if(game==='scratch'&&Number(d.payout)>0)p.collections.scratch[String(Number(d.payout))]=true;if(game==='slots'&&Number(d.payout)>0&&BASE_SLOT.includes(d.symbol))p.collections.slots[d.symbol]=true;if(game==='auction'&&d.won)for(const c of (Array.isArray(d.categories)?d.categories:[]))if(BASE_AUCTION.includes(c))p.collections.auction[c]=true;unlockCheck(game,p);writeProfile(p);return p}
function award(game,amount){amount=Math.max(0,Math.floor(Number(amount)||0));if(!amount)return wallet();const w=wallet(),p=profile();p.earned[game]=(Number(p.earned[game])||0)+amount;writeProfile(p);return setBalance(w.balance+amount,w.totalEarned+amount)}
function roll(game){const p=profile();if(!p.unlocks[game])return 0;const advanced=!!p.advanced[game],r=Math.random();let amount=0;if(game==='fishing'&&r<(advanced?.02:.01))amount=advanced?2:1;if(game==='scratch'&&r<(advanced?.04:.025))amount=advanced?2:1;if(game==='slots'&&r<(advanced?.025:.0125))amount=advanced&&r<.0125?3:1;if(game==='auction'&&r<(advanced?.16:.09))amount=advanced?2:1;if(amount){award(game,amount);showDrop(game,amount,advanced)}return amount}
function showDrop(game,amount,advanced=false){let host=document.getElementById('airp-token-drop');if(!host){host=document.createElement('div');host.id='airp-token-drop';host.innerHTML='<img><b></b><span>街机代币</span>';document.body.append(host)}host.querySelector('img').src=advanced?'assets/token/star-fragment.svg':ICON[game];host.querySelector('b').textContent=`+${amount}`;host.classList.remove('show');void host.offsetWidth;host.classList.add('show');clearTimeout(host._timer);host._timer=setTimeout(()=>host.classList.remove('show'),1900)}
function inject(){if(document.getElementById('airp-token-style'))return;const s=document.createElement('style');s.id='airp-token-style';s.textContent=`#airp-token-drop{position:fixed;z-index:20000;left:50%;top:18%;display:grid;grid-template-columns:56px auto;grid-template-rows:auto auto;align-items:center;gap:0 10px;padding:10px 17px 10px 10px;border:2px solid #ffe69a88;border-radius:18px;background:linear-gradient(145deg,#211b3bea,#102b3bea);box-shadow:0 18px 50px #000a,inset 0 1px #fff5;transform:translate(-50%,-18px) scale(.82);opacity:0;pointer-events:none}#airp-token-drop img{grid-row:1/3;width:56px;height:56px;filter:drop-shadow(0 0 11px #7effee)}#airp-token-drop b{color:#ffe289;font:1000 24px/1 ui-monospace,Consolas,monospace}#airp-token-drop span{color:#d8d2ec;font-size:10px;font-weight:900;letter-spacing:.1em}#airp-token-drop.show{animation:airp-token-pop 1.9s ease forwards}@keyframes airp-token-pop{0%{opacity:0;transform:translate(-50%,-18px) scale(.7)}18%,72%{opacity:1;transform:translate(-50%,0) scale(1)}100%{opacity:0;transform:translate(-50%,-12px) scale(.92)}}`;document.head.append(s)}
inject();addEventListener('airp-fishing:settled',e=>{record('fishing',e.detail);if(e.detail?.captured)roll('fishing')});addEventListener('airp-scratch:settled',e=>{record('scratch',e.detail);roll('scratch')});addEventListener('airp-slot:settled',e=>{record('slots',e.detail);roll('slots')});addEventListener('airp-auction:settled',e=>{record('auction',e.detail);if(e.detail?.won)roll('auction')});window.AIRPToken=Object.freeze({profile,wallet,record,roll,award,goals:{...GOALS},advanced:{...ADVANCED},isUnlocked:g=>!!profile().unlocks[g]});})();
